name: Build,test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  #schedule:
  #  - cron: '0 0 * * 0' # weekly

jobs:
  build:

    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.6, 3.7, 3.8, 3.9]
        os: [ubuntu-latest, macos-latest, windows-latest]
        platform: [x64]
        include:
          - python-version: 3.8
            os: windows-latest
            platform: x86
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
        architecture: ${{ matrix.platform }}
    - name: Install prerequisits
      run: |
        set -ex
        python -m pip install --upgrade pip
        python -m pip install --progress-bar=off  -r ci/requirements.txt
        echo $(python -c"import sys; print(sys.version)")
    - name: Build and install
      run: |
        set -ex
        python -m pip install .
    - name: Test
      run: |
        python -m pip install -r test_requirements.txt
        python -m pytest tests -vv --durations 10 

  build_docs:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - uses: actions/checkout@v2
      with:
        submodules: recursive
        fetch-depth: 0

    - name: build docs
      run: |
        set -ex
        python -m pip install .
        pushd doc_src
        python -m pip install --progress-bar=off -r doc_requirements.txt
        make html
        popd
    - name: store docs
      uses: actions/upload-artifact@v2
      with:
        name: docs
        path: doc_src/build/html
